
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zahan
 */
public class Celeb_main extends javax.swing.JFrame {

    /**
     * Creates new form Celeb_main
     */
    public Celeb_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        Angel_pic = new javax.swing.JLabel();
        Angel_cart = new javax.swing.JButton();
        Angel_price = new javax.swing.JTextField();
        Diego_pic = new javax.swing.JLabel();
        Eli_pic = new javax.swing.JLabel();
        Emma_pic = new javax.swing.JLabel();
        Keanu_pic = new javax.swing.JLabel();
        Leo_pic = new javax.swing.JLabel();
        MJ_pic = new javax.swing.JLabel();
        RDJ_pic = new javax.swing.JLabel();
        Rowan_pic = new javax.swing.JLabel();
        Vinci_pic = new javax.swing.JLabel();
        Angel12 = new javax.swing.JTextField();
        Diego_price = new javax.swing.JTextField();
        Angel13 = new javax.swing.JTextField();
        Diego_cart = new javax.swing.JButton();
        Angel15 = new javax.swing.JTextField();
        Eli_price = new javax.swing.JTextField();
        Eli_cart = new javax.swing.JButton();
        Angel17 = new javax.swing.JTextField();
        Angel30 = new javax.swing.JTextField();
        Rowan_price = new javax.swing.JTextField();
        Angel31 = new javax.swing.JTextField();
        RDJ_price = new javax.swing.JTextField();
        RDJ_cart = new javax.swing.JButton();
        Angel32 = new javax.swing.JTextField();
        Vinci_price = new javax.swing.JTextField();
        Rowan_cart = new javax.swing.JButton();
        Angel33 = new javax.swing.JTextField();
        Hitler_price = new javax.swing.JTextField();
        Hitler_cart = new javax.swing.JButton();
        Hitler_pic = new javax.swing.JLabel();
        Angel34 = new javax.swing.JTextField();
        Heath_price = new javax.swing.JTextField();
        Heath_cart = new javax.swing.JButton();
        Heath_pic = new javax.swing.JLabel();
        Angel35 = new javax.swing.JTextField();
        Emma_price = new javax.swing.JTextField();
        Emma_cart = new javax.swing.JButton();
        Angel36 = new javax.swing.JTextField();
        MJ_price = new javax.swing.JTextField();
        MJ_cart = new javax.swing.JButton();
        Angel37 = new javax.swing.JTextField();
        Leo_price = new javax.swing.JTextField();
        Leo_cart = new javax.swing.JButton();
        Vinci = new javax.swing.JButton();
        Angel38 = new javax.swing.JTextField();
        Keanu_price = new javax.swing.JTextField();
        Keanu_cart = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Argenté ");
        setFocusable(false);
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Vivaldi", 0, 10)); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Vivaldi", 1, 40)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Argenté ");

        Angel_pic.setIcon(new javax.swing.ImageIcon("./angel1.jpg")); // NOI18N

        Angel_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Angel_cart.setText("Go to Cart");
        Angel_cart.setInheritsPopupMenu(true);
        Angel_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel_cartActionPerformed(evt);
            }
        });

        Angel_price.setBackground(new java.awt.Color(60, 63, 65));
        Angel_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Angel_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel_price.setText("₹90,000");
        Angel_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel_priceActionPerformed(evt);
            }
        });

        Diego_pic.setIcon(new javax.swing.ImageIcon("./Diego.jpg")); // NOI18N

        Eli_pic.setIcon(new javax.swing.ImageIcon("./Eli.jpg")); // NOI18N

        Emma_pic.setIcon(new javax.swing.ImageIcon("./Emma.jpg")); // NOI18N

        Keanu_pic.setIcon(new javax.swing.ImageIcon("./keanu.jpg")); // NOI18N

        Leo_pic.setIcon(new javax.swing.ImageIcon("./leo.jpg")); // NOI18N

        MJ_pic.setIcon(new javax.swing.ImageIcon("./MJ.jpg")); // NOI18N

        RDJ_pic.setIcon(new javax.swing.ImageIcon("./RDJ.jpg")); // NOI18N

        Rowan_pic.setIcon(new javax.swing.ImageIcon("./Rowan.jpg")); // NOI18N

        Vinci_pic.setIcon(new javax.swing.ImageIcon("./vinci.jpg")); // NOI18N

        Angel12.setEditable(false);
        Angel12.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel12.setText("Angelina Jolie");
        Angel12.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel12ActionPerformed(evt);
            }
        });

        Diego_price.setBackground(new java.awt.Color(60, 63, 65));
        Diego_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Diego_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Diego_price.setText("₹4,30,000");
        Diego_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Angel13.setEditable(false);
        Angel13.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        Angel13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel13.setText("Diego Maradona");
        Angel13.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel13ActionPerformed(evt);
            }
        });

        Diego_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Diego_cart.setText("Go to Cart");
        Diego_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diego_cartActionPerformed(evt);
            }
        });

        Angel15.setEditable(false);
        Angel15.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel15.setText("Queen Elizabeth II");
        Angel15.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel15ActionPerformed(evt);
            }
        });

        Eli_price.setBackground(new java.awt.Color(60, 63, 65));
        Eli_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Eli_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eli_price.setText("₹6,75,000");
        Eli_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Eli_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Eli_cart.setText("Go to Cart");
        Eli_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eli_cartActionPerformed(evt);
            }
        });

        Angel17.setEditable(false);
        Angel17.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel17.setText("Diego Maradona");
        Angel17.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel17ActionPerformed(evt);
            }
        });

        Angel30.setEditable(false);
        Angel30.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel30.setText("Rowan Atkinson");
        Angel30.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel30ActionPerformed(evt);
            }
        });

        Rowan_price.setBackground(new java.awt.Color(60, 63, 65));
        Rowan_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Rowan_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Rowan_price.setText("₹1,40,000");
        Rowan_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Angel31.setEditable(false);
        Angel31.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel31.setText("Robert Downey Jr.");
        Angel31.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel31ActionPerformed(evt);
            }
        });

        RDJ_price.setBackground(new java.awt.Color(60, 63, 65));
        RDJ_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        RDJ_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RDJ_price.setText("₹1,50,000");
        RDJ_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        RDJ_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        RDJ_cart.setText("Go to Cart");
        RDJ_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDJ_cartActionPerformed(evt);
            }
        });

        Angel32.setEditable(false);
        Angel32.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel32.setText("Leonardo da Vinci");
        Angel32.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel32ActionPerformed(evt);
            }
        });

        Vinci_price.setBackground(new java.awt.Color(60, 63, 65));
        Vinci_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Vinci_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vinci_price.setText("₹8,25,000");
        Vinci_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Rowan_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Rowan_cart.setText("Go to Cart");
        Rowan_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rowan_cartActionPerformed(evt);
            }
        });

        Angel33.setEditable(false);
        Angel33.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel33.setText("Adolf Hitler");
        Angel33.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel33ActionPerformed(evt);
            }
        });

        Hitler_price.setBackground(new java.awt.Color(60, 63, 65));
        Hitler_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Hitler_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hitler_price.setText("₹12,00,000");
        Hitler_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Hitler_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Hitler_cart.setText("Go to Cart");
        Hitler_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hitler_cartActionPerformed(evt);
            }
        });

        Hitler_pic.setIcon(new javax.swing.ImageIcon("./Hitler.jpg")); // NOI18N

        Angel34.setEditable(false);
        Angel34.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel34.setText("Heath Ledger");
        Angel34.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel34ActionPerformed(evt);
            }
        });

        Heath_price.setBackground(new java.awt.Color(60, 63, 65));
        Heath_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Heath_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Heath_price.setText("₹1,20,000");
        Heath_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Heath_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heath_priceActionPerformed(evt);
            }
        });

        Heath_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Heath_cart.setText("Go to Cart");
        Heath_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heath_cartActionPerformed(evt);
            }
        });

        Heath_pic.setIcon(new javax.swing.ImageIcon("./heath.jpg")); // NOI18N

        Angel35.setEditable(false);
        Angel35.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel35.setText("Emma Stone");
        Angel35.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel35ActionPerformed(evt);
            }
        });

        Emma_price.setBackground(new java.awt.Color(60, 63, 65));
        Emma_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Emma_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Emma_price.setText("₹65,000");
        Emma_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Emma_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Emma_cart.setText("Go to Cart");
        Emma_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emma_cartActionPerformed(evt);
            }
        });

        Angel36.setEditable(false);
        Angel36.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel36.setText("Michael Jackson");
        Angel36.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel36ActionPerformed(evt);
            }
        });

        MJ_price.setBackground(new java.awt.Color(60, 63, 65));
        MJ_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        MJ_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MJ_price.setText("₹4,50,000");
        MJ_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        MJ_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MJ_priceActionPerformed(evt);
            }
        });

        MJ_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        MJ_cart.setText("Go to Cart");
        MJ_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MJ_cartActionPerformed(evt);
            }
        });

        Angel37.setEditable(false);
        Angel37.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel37.setText("Leonardo DiCaprio");
        Angel37.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel37ActionPerformed(evt);
            }
        });

        Leo_price.setBackground(new java.awt.Color(60, 63, 65));
        Leo_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Leo_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Leo_price.setText("₹1,70,000");
        Leo_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Leo_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Leo_cart.setText("Go to Cart");
        Leo_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leo_cartActionPerformed(evt);
            }
        });

        Vinci.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Vinci.setText("Go to Cart");
        Vinci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VinciActionPerformed(evt);
            }
        });

        Angel38.setEditable(false);
        Angel38.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        Angel38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angel38.setText("Keanu Reeves");
        Angel38.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Angel38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angel38ActionPerformed(evt);
            }
        });

        Keanu_price.setBackground(new java.awt.Color(60, 63, 65));
        Keanu_price.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Keanu_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Keanu_price.setText("₹1,20,000");
        Keanu_price.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Keanu_cart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Keanu_cart.setText("Go to Cart");
        Keanu_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Keanu_cartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addComponent(jTextField1)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(135, 135, 135)
                                                                .addComponent(Diego_cart))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Angel17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                168,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Angel12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                168,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(295, 295, 295)
                                                .addComponent(Hitler_cart))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(Eli_cart)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(173, 173, 173)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        false)
                                                                                        .addGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout.createSequentialGroup()
                                                                                                        .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(
                                                                                                                        layout.createSequentialGroup()
                                                                                                                                .addComponent(
                                                                                                                                        Angel34,
                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                        168,
                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(0,
                                                                                                                                        0,
                                                                                                                                        Short.MAX_VALUE))
                                                                                                                .addGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                        layout.createSequentialGroup()
                                                                                                                                .addGap(0,
                                                                                                                                        0,
                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                .addComponent(
                                                                                                                                        Heath_cart)))
                                                                                                        .addGap(18, 18,
                                                                                                                18)
                                                                                                        .addComponent(
                                                                                                                Heath_price,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(Heath_pic,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(Angel33,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                168,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(86, 86, 86)
                                                                                        .addComponent(Hitler_price,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(Hitler_pic)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(303, 303, 303)
                                                                .addComponent(Keanu_cart))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(Eli_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(71, 71, 71)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(Angel38,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        168,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(Keanu_price,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(Keanu_pic)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Angel_pic)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Diego_pic,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(Eli_pic)
                                                                .addComponent(Angel15,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 168,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Angel_cart)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Angel_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Diego_price,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                layout.createSequentialGroup()
                                                                        .addGap(123, 123, 123)
                                                                        .addComponent(MJ_cart)
                                                                        .addGap(291, 291, 291)
                                                                        .addComponent(Emma_cart)
                                                                        .addContainerGap(
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(Angel30,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        168,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(86, 86, 86)
                                                                                                .addComponent(
                                                                                                        Rowan_price,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(Rowan_pic))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGap(140, 140, 140)
                                                                                        .addComponent(RDJ_cart))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                        .addGroup(layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        Angel36,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        168,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        Short.MAX_VALUE)
                                                                                                                .addComponent(
                                                                                                                        MJ_price,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(
                                                                                                                        layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(
                                                                                                                                        RDJ_price,
                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(
                                                                                                                                        RDJ_pic))
                                                                                                                .addComponent(
                                                                                                                        Angel31,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        168,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addComponent(MJ_pic))
                                                                                        .addGap(63, 63, 63)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                        .addGroup(layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        Angel37,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        168,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        Short.MAX_VALUE)
                                                                                                                .addComponent(
                                                                                                                        Leo_price,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                layout.createSequentialGroup()
                                                                                                                        .addGap(0,
                                                                                                                                0,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                        .addComponent(
                                                                                                                                Leo_cart)
                                                                                                                        .addGap(112,
                                                                                                                                112,
                                                                                                                                112))
                                                                                                        .addComponent(
                                                                                                                Leo_pic)
                                                                                                        .addGroup(layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        Angel35,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        168,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        Short.MAX_VALUE)
                                                                                                                .addComponent(
                                                                                                                        Emma_price,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addComponent(
                                                                                                                Emma_pic))
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                        .addGroup(layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        Angel32,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        168,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        Short.MAX_VALUE)
                                                                                                                .addComponent(
                                                                                                                        Vinci_price,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addComponent(
                                                                                                                Vinci_pic)))))
                                                                .addGap(0, 24, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(196, 196, 196)
                                                .addComponent(Rowan_cart)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Vinci)
                                                .addGap(134, 134, 134))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Angel13, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(1392, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Angel_pic)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Angel12,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(Angel_cart)
                                                                        .addComponent(Heath_cart)))
                                                        .addComponent(Angel_price,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Heath_pic)
                                                        .addComponent(Emma_pic)
                                                        .addComponent(MJ_pic,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Heath_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Angel36)
                                                                .addComponent(MJ_price))
                                                        .addComponent(Angel34, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Emma_price,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Angel35,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(MJ_cart)
                                                                        .addComponent(Emma_cart))))))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Diego_pic)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(Diego_price,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                33,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(Angel33,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(Hitler_price,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(Angel31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(Angel17,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                25,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(6, 6, 6))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Hitler_pic)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Diego_cart)
                                                        .addComponent(Hitler_cart)
                                                        .addComponent(RDJ_cart))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Eli_pic)
                                                        .addComponent(Keanu_pic)
                                                        .addComponent(Rowan_pic, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Vinci_pic, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Angel15, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Angel38,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Keanu_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Eli_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Angel30,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Rowan_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Angel32,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Vinci_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Leo_pic)
                                                        .addComponent(RDJ_pic))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(RDJ_price,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Angel37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(Leo_price,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Leo_cart)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Eli_cart)
                                                .addComponent(Keanu_cart))
                                        .addComponent(Rowan_cart, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Vinci, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(9, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(677, 677, 677)
                                        .addComponent(Angel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(290, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Angel38ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel12ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel13ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel15ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel17ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel30ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel31ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel32ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel33ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel34ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel35ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel36ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// G

    private void Angel37ActionPerformed(java.awt.event.ActionEvent e) {
        Celeb c = new Celeb();
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }

    private void Angel_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Angel_cartActionPerformed
        // TODO add your handling code here:
        Celeb c = new Celeb();

        c.Img.setIcon(new javax.swing.ImageIcon("./angel1.jpg")); // This
                                                                                                                   // line
                                                                                                                   // would
        c.setVisible(true);

        Celeb.Price_celeb.setText(Celeb_main.Angel_price.getText());
        dispose();
    }// GEN-LAST:event_Angel_cartActionPerformed

    private void Diego_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Diego_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Diego_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Diego.jpg"));

        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Diego_cartActionPerformed

    private void Eli_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Eli_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Eli_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Eli.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Eli_cartActionPerformed

    private void Heath_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Heath_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Heath_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Heath.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Heath_cartActionPerformed

    private void Hitler_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Hitler_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Hitler_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Hitler.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Hitler_cartActionPerformed

    private void Keanu_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Keanu_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Keanu_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Keanu.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Keanu_cartActionPerformed

    private void MJ_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MJ_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.MJ_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./MJ.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_MJ_cartActionPerformed

    private void RDJ_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RDJ_cartActionPerformed
        Celeb c = new Celeb();
        Celeb.Price_celeb.setText(Celeb_main.RDJ_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./RDJ.jpg"));
        c.setVisible(true);
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_RDJ_cartActionPerformed

    private void Rowan_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Rowan_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Rowan_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Rowan.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Rowan_cartActionPerformed

    private void Emma_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Emma_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Emma_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Emma.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Emma_cartActionPerformed

    private void Leo_cartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Leo_cartActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Leo_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Leo.jpg"));
        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Leo_cartActionPerformed

    private void VinciActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VinciActionPerformed
        Celeb c = new Celeb();
        c.setVisible(true);
        Celeb.Price_celeb.setText(Celeb_main.Vinci_price.getText());
        c.Img.setIcon(new javax.swing.ImageIcon("./Vinci.jpg"));

        dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_VinciActionPerformed

    private void Angel_priceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Angel_priceActionPerformed

        // TODO add your handling code here:
    }// GEN-LAST:event_Angel_priceActionPerformed

    private void Heath_priceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Heath_priceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_Heath_priceActionPerformed

    private void MJ_priceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MJ_priceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_MJ_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * FlatLightLaf.setup();
         * 
         * try {
         * UIManager.setLookAndFeel( new FlatDarkLaf() );
         * }
         * catch( UnsupportedLookAndFeelException ex ) {
         * System.err.println( "Failed to initialize LaF" );
         * }
         */

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Celeb_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Angel12;
    private javax.swing.JTextField Angel13;
    private javax.swing.JTextField Angel15;
    private javax.swing.JTextField Angel17;
    private javax.swing.JTextField Angel30;
    private javax.swing.JTextField Angel31;
    private javax.swing.JTextField Angel32;
    private javax.swing.JTextField Angel33;
    private javax.swing.JTextField Angel34;
    private javax.swing.JTextField Angel35;
    private javax.swing.JTextField Angel36;
    private javax.swing.JTextField Angel37;
    private javax.swing.JTextField Angel38;
    private javax.swing.JButton Angel_cart;
    public javax.swing.JLabel Angel_pic;
    public static javax.swing.JTextField Angel_price;
    private javax.swing.JButton Diego_cart;
    private javax.swing.JLabel Diego_pic;
    public static javax.swing.JTextField Diego_price;
    private javax.swing.JButton Eli_cart;
    private javax.swing.JLabel Eli_pic;
    public static javax.swing.JTextField Eli_price;
    private javax.swing.JButton Emma_cart;
    private javax.swing.JLabel Emma_pic;
    public static javax.swing.JTextField Emma_price;
    private javax.swing.JButton Heath_cart;
    private javax.swing.JLabel Heath_pic;
    public static javax.swing.JTextField Heath_price;
    private javax.swing.JButton Hitler_cart;
    private javax.swing.JLabel Hitler_pic;
    public static javax.swing.JTextField Hitler_price;
    private javax.swing.JButton Keanu_cart;
    private javax.swing.JLabel Keanu_pic;
    public static javax.swing.JTextField Keanu_price;
    private javax.swing.JButton Leo_cart;
    private javax.swing.JLabel Leo_pic;
    public static javax.swing.JTextField Leo_price;
    private javax.swing.JButton MJ_cart;
    public javax.swing.JLabel MJ_pic;
    public static javax.swing.JTextField MJ_price;
    private javax.swing.JButton RDJ_cart;
    private javax.swing.JLabel RDJ_pic;
    public static javax.swing.JTextField RDJ_price;
    private javax.swing.JButton Rowan_cart;
    private javax.swing.JLabel Rowan_pic;
    public static javax.swing.JTextField Rowan_price;
    private javax.swing.JButton Vinci;
    private javax.swing.JLabel Vinci_pic;
    public static javax.swing.JTextField Vinci_price;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
